services:
  windows:
    image: dockurr/windows
    container_name: windows10
    entrypoint:
      - /bin/sh
      - -c
      - |
        ip route del default
        tini -s /run/entry.sh
    environment:
      VERSION: "10"
      DISK_SIZE: "256G"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      USERNAME: "kaylor"
      PASSWORD: " "
      ARGUMENTS: "-device qemu-xhci -device usb-host,vendorid=0x0c66,productid=0x000c"
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/bus/usb
    cap_add:
      - NET_ADMIN
    ports:
      - 8008:8006
      - 13391:3389/tcp
      - 13391:3389/udp
    volumes:
      - ./windows10:/storage
      - /mnt/data/windows:/data
    restart: always
    stop_grace_period: 2m
