services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      DISK_SIZE: "256G"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      USERNAME: "kaylor"
      PASSWORD: "  "
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 13389:3389/tcp
      - 13389:3389/udp
    volumes:
      - ./windows:/storage
      - /mnt/data/windows:/data
    restart: always
    stop_grace_period: 2m
