FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
# ENV TZ=Asia/Shanghai
# 维护者
LABEL maintainer="kaylor.chen@qq.com"

RUN apt update && \
    apt install -y --no-install-recommends python3 python-is-python3 && \
    apt install -y --no-install-recommends python3-dev python3-pip gcc vim libprotobuf-dev zlib1g zlib1g-dev libsm6 && \
    apt install -y --no-install-recommends libgl1 libglib2.0-0 android-tools-adb && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY rk3588_onnx2rknn/rknn_toolkit2-2.0.0b12+1fc94019-cp310-cp310-linux_x86_64.whl rknn_toolkit2-2.0.0b12+1fc94019-cp310-cp310-linux_x86_64.whl

RUN pip3 install rknn_toolkit2-2.0.0b12+1fc94019-cp310-cp310-linux_x86_64.whl

COPY rk3588_onnx2rknn/requirements-beta.txt requirements-beta.txt

RUN pip3 install -r requirements-beta.txt