services:
  windows:
    image: dockurr/windows
    container_name: windows10
    entrypoint:
      - /bin/sh
      - -c
      - |
        ip route del default
        tini -s /run/entry.sh
    environment:
      TZ: Asia/Shanghai
      VERSION: "10"
      DISK_SIZE: "256G"
      RAM_SIZE: "10G"
      CPU_CORES: "10"
      USERNAME: "kaylor"
      PASSWORD: " "
      ARGUMENTS: "-device vfio-pci,host=17:00.0,multifunction=on"
      # ARGUMENTS: "-device qemu-xhci -device usb-host,vendorid=0x05e3,productid=0x0626 -device usb-host,vendorid=0x05e3,productid=0x0610"
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/bus/usb
      - /dev/vfio
    cap_add:
      - NET_ADMIN
      - IPC_LOCK
    ports:
      - 8008:8006
      - 13391:3389/tcp
      - 13391:3389/udp
    volumes:
      - ./windows10:/storage
      - /mnt/data/windows:/data
    #restart: always
    stop_grace_period: 2m
