networks:
  windows-bridge:
    external: true
    name: windows-bridge
services:
  windows:
    image: dockurr/windows
    container_name: windows11
    networks:
      windows-bridge:
        ipv4_address: 192.168.10.3
    environment:
      VERSION: "11"
      DISK_SIZE: "256G"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      USERNAME: "kaylor"
      PASSWORD: " "
      # ARGUMENTS: "-device qemu-xhci -device usb-host,vendorid=0x0c66,productid=0x000c"
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/bus/usb
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 13389:3389/tcp
      - 13389:3389/udp
    volumes:
      - ./windows11:/storage
      - /mnt/data/windows:/data
    # restart: always
    stop_grace_period: 2m
