name: Build and push OpenWrt evn image

on:
  push:
    paths:
      - 'openwrt/Dockerfile'
  pull_request:
    paths:
      - 'openwrt/Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: openwrt/Dockerfile
          push: true
          tags: kaylor/openwrt_compile_env
          platforms: linux/amd64

      - name: Logout of DockerHub
        run: docker logout