name: Build and push multi-arch ubuntu-3588-rootfs Docker image

on:
  push:
    paths:
      - 'ubuntu-3588-rootfs/Dockerfile_ROS2'
  pull_request:
    paths:
      - 'ubuntu-3588-rootfs/Dockerfile_ROS2'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files
        run: |
          cp ubuntu-3588-rootfs/kaylor-keyring.gpg ./
          cp ubuntu-3588-rootfs/rk3588-kaylor.list ./

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ubuntu-3588-rootfs/Dockerfile_ROS2
          push: true
          tags: kaylor/ubuntu-3588-rootfs:humble-ros-base-jammy
          platforms: linux/arm64

      - name: Logout of DockerHub
        run: docker logout