name: Build and push l4t r36.3 base Docker image

on:
  push:
    paths:
      - 'l4t-base/Dockerfile_r36.3_base'
      - 'l4t-base/packages_l4t.list'
  pull_request:
    paths:
      - 'l4t-base/packages_l4t.list'
      - 'l4t-base/Dockerfile_r36.3_base'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: l4t-base/Dockerfile_r36.3_base
          push: true
          tags: kaylor/l4t-base:r36.3.0_base
          platforms: linux/arm64

      - name: Logout of DockerHub
        run: docker logout